apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "chal"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/challenge: localhost/ctf-profile
    spec:
      containers:
      - name: "challenge"
        image: "challenge"
        ports:
        - containerPort: 1337
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
          readOnlyRootFilesystem: true
        command:
        resources:
          limits:
            cpu: "0.9"
          requests:
            cpu: "0.45"
        volumeMounts:
        - name: "secrets"
          mountPath: "/secrets"
          readOnly: true
        - name: "config"
          mountPath: "/config"
          readOnly: true
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 45
          timeoutSeconds: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 30
      - name: "healthcheck"
        image: "healthcheck"
        command:
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.05"
        volumeMounts:
        - name: "healthcheck-secrets"
          mountPath: "/secrets"
          readOnly: true
        - name: "healthcheck-exploit-key"
          mountPath: "/keys"
          readOnly: true
        - name: "healthcheck-config"
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: "secrets"
        secret:
          secretName: "secrets"
          defaultMode: 0444
      - name: "config"
        configMap:
          name: "config"
      - name: "healthcheck-secrets"
        secret:
          secretName: "healthcheck-secrets"
          defaultMode: 0444
      - name: "healthcheck-exploit-key"
        secret:
          secretName: "healthcheck-exploit-key"
          defaultMode: 0444
      - name: "healthcheck-config"
        configMap:
          name: "healthcheck-config"
