apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "chal"
spec:
  template:
    spec:
      volumes:
      - name: "secrets"
        secret:
          secretName: "challenge-skeleton-secrets"
      - name: "config"
        configMap:
          name: "challenge-skeleton-config"
